import type { PluginIconKey } from '@/lib/plugins/manifest-schema';
import type { PluginUiIconName } from '@/lib/plugins/ui-tree';
import {
	ArrowDown,
	ArrowLeft,
	ArrowRight,
	ArrowUp,
	BarChart3,
	BookOpen,
	Calendar,
	Check,
	Columns3,
	FileText,
	Flag,
	Gauge,
	GitPullRequest,
	Lightbulb,
	ListChecks,
	Minus,
	Pause,
	Play,
	Plus,
	Puzzle,
	RefreshCw,
	Scale,
	Star,
	Target,
	Timer,
	Users,
	Wallet,
	X,
	type LucideIcon,
} from 'lucide-react';

/** Icons for plugins and their node kinds (manifest `icon`). */
export const PLUGIN_ICONS: Record<PluginIconKey, LucideIcon> = {
	gauge: Gauge,
	columns: Columns3,
	puzzle: Puzzle,
	target: Target,
	chart: BarChart3,
	'list-checks': ListChecks,
	calendar: Calendar,
	timer: Timer,
	flag: Flag,
	star: Star,
	lightbulb: Lightbulb,
	'file-text': FileText,
	wallet: Wallet,
	scale: Scale,
	git: GitPullRequest,
	book: BookOpen,
	users: Users,
};

/** Icons a plugin can draw inside its node (buttons and `icon` primitives). */
export const PLUGIN_UI_ICONS: Record<PluginUiIconName, LucideIcon> = {
	plus: Plus,
	minus: Minus,
	check: Check,
	x: X,
	refresh: RefreshCw,
	play: Play,
	pause: Pause,
	'arrow-up': ArrowUp,
	'arrow-down': ArrowDown,
	'arrow-left': ArrowLeft,
	'arrow-right': ArrowRight,
	star: Star,
	flag: Flag,
	target: Target,
};
